Revert "core/Makefile: start building ubuntu-boot.img with ubuntu-touch specific initrd"
This reverts commit bcc9e8af0eab321a2924149ba9e4028d2d665c41.

Reverting due to build issues:
Target boot image for Ubuntu Touch: ../out/target/product/maguro/ubuntu-boot.img
error: could not load ramdisk '../out/target/product/maguro/ubuntu-ramdisk.img'
make: *** [../out/target/product/maguro/ubuntu-boot.img] Error 1

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>